### ISSUE TITLE
Bitrate & iframe interval

### ISSUE THREAD

**Issue by rcvangemert** [JohanBlome/encapp#185]
Johan, A Question!
My app uses the android encoder for mp4 recording and streaming. I struggle to see the difference in quality or motion artefacts as I vary bitrare (tried 500k to 4meg) and iframe interval (tried 1 to 5). Should It be very obvious or is it suttle?

**Comment by JohanBlome** [comment]
HelloSorry for not answering before.What you can check is the qp values per frame. If the value is low and stay consistent with increased bitrate you just have too little detail information and a lower bitrate is sufficient.Kind Regards Johan BlomeOn May 19, 2023 15:37, Robert Van Gemert ***@***.***> wrote:
After a bit more testing 2 of my samsung devices default to 4mbit, and 2 of my hp devices (chromebook android) work as expected. The lower the bitrate the more pixilazation.
