### ISSUE TITLE
object has not attribute dry_run

### ISSUE THREAD

**Issue by russellanam** [JohanBlome/encapp#186]
Hi,

After installation when I run the command:

`/scripts/encapp.py run tests/bitrate_buffer.pbtxt --local-workdir /tmp/test -e input.filepath /tmp/akiyo_qcif.y4m`

I get error:

`Traceback (most recent call last):
  File "/oppo/encapp/./scripts/encapp.py", line 1709, in <module>
    main(sys.argv)
  File "/oppo/encapp/./scripts/encapp.py", line 1699, in main
    result_ok, result_json = codec_test(options, model, serial, options.debug)
  File "/oppo/encapp/./scripts/encapp.py", line 1189, in codec_test
    return run_codec_tests_file(
  File "/oppo/encapp/./scripts/encapp.py", line 538, in run_codec_tests_file
    if options.dry_run:
AttributeError: 'Namespace' object has no attribute 'dry_run'
`

**Comment by JohanBlome** [comment]
Sorry. Missed this issue. 
I do not see the same error but the "dry_run" option does not work either s o there is clearly a problem.
I can run:
"
python3 scripts/encapp.py run tests/bitrate_buffer.pbtxt --local-workdir bitrate_buffer -e input.filepath /tmp/akiyo_qcif.y4m 
"
But if I add "-dry_run" it fails. I'll fix that.
