### ISSUE TITLE
Hardcoded reference to /sdcard

### ISSUE THREAD

**Issue by hidekimendoza** [JohanBlome/encapp#92]
Based on ./gradlew lint comments:
Your code should not reference the /sdcard path directly; instead use Environment.getExternalStorageDirectory().getPath().
More info: https://developer.android.com/training/data-storage#filesExternal
To suppress this error, use the issue id "SdCardPath" as explained in the [Suppressing Warnings and Errors]

https://github.com/JohanBlome/encapp/blob/bf485d19cc31201a28f7d22a25c4bcc61a183604/app/src/main/java/com/facebook/encapp/MainActivity.java#L161

To retreive path on python scripts:
```
adb shell 'echo $EXTERNAL_STORAGE'
```

**Comment by JohanBlome** [comment]
OK. We can do that. Need to add something in README about it.
